---
title: "Применение средств и методов OSINT"
author: Tyvan Maxim BISO-02-20
format:
    md:
        output-file: README.md
engine: knitr
---

# Применение средств и методов OSINT
Tyvan Maxim BISO-02-20

## Цель работы

1.  Освоить базовые подходы процессов OSINT
2.  Освоить современные инструменты поиска и сбора информации
3.  Освоить инструменты совместной работы в ходе аналитической деятельности

## Ход работы

В качестве объекта развездки была выбрана компания ДиалогНаука занимающаяся поставкой программных и аппаратных систем защиты информации производства ведущих отечественных компаний.

## Шаг 1. Инфорация о компании

Акционерное общество «ДиалогНаука» создано 31 января 1992 года. Учредителями компании были СП «Диалог» и Вычислительный центр Российской Академии наук.
«ДиалогНаука» является членом Ассоциации защиты информации (АЗИ), Ассоциации документальной электросвязи (АДЭ), Ассоциации «АБИСС», а также действующим участником Программы ассоциированных консультантов BSI ACP.

Юридический адрес компании - 105066, город Москва, Елоховский пр-д, д. 3 стр. 2
Адрес представленный на официальном сайте - 115230, г. Москва, 1-й Нагатинский проезд, д.10, стр.1, БЦ "Ньютон Плаза", 11 этаж, АО "ДиалогНаука"

Информация взята с сайтов - https://www.dialognauka.ru/about/ и https://www.rusprofile.ru/id/3758984

## Шаг 2. Направленность компании

Основная направленность компании - поставка программных и аппаратных средств защиты информации от вируса, спама, сетевых атак, утечки конфиденциальной информации и других угроз ИБ.

Услуги и решения предоставляемые компанией:

### Тестирование на проникновение и анализ защищенности

-Тестирование на проникновение в рамках выполнения требования Положений Банка России по защите информации, требований SWIFT CSP, требований PCI DSS

-Аудит Интернет-порталов и web-приложений

-Анализ безопасности мобильных приложений

-Аудит безопасности беспроводных сетей

-Внутреннее тестирование на проникновение

-Проведение тестирования на проникновение с целью оценки защищенности от внешних угроз

### Защита персональных данных
-Подготовка к проверке и сопровождение при проверках регуляторов

-Аттестация ИСПДн/Оценка соответствия

-Разработка комплекта организационно-распорядительных документов по обеспечению безопасности ПДн

-Разработка технического задания и технического проекта на создание СЗПДн

-Разработка модели нарушителя и угроз безопасности ПДн

-Обследование и оценка выполнения требований GDPR

-Обследование и оценка уровня защиты ПДн

### Обеспечение соответствия ISO 27001

«ДиалогНаука» является действующим участником Программы ассоциированных консультантов BSI ACP и оказывает услуги по разработке и внедрению СУИБ. 

### Услуги в области стандартов по обеспечению информационной безопасности кредитно-финансовых организаций

-Оценка соответствия системы управления рисками информационной безопасности требованиям Положения Банка России 716-П

-Проведение ASV-сканирований уязвимостей информационной инфраструктуры в соответствии с требованиями PCI DSS

-Оценка соответствия / Приведение в соответствие с PCI DSS, PCI 3DS, PCI PIN Security

-Оценка соответствия / Приведение в соответствие требованиям SWIFT Customer Security Programme

-Оценка соответствия / Приведение в соответствие требованиям Банка России по информационной безопасности (Положения Банка России 683-П, 719-П, 747-П, 757-П, национальный стандарт ГОСТ Р 57580.1-2017)

### Комплексный аудит ИБ

-Оценка уровня зрелости ситуационных центров по информационной безопасности

-Проведение комплексного аудита информационной безопасности, включающего в себя инструментальный аудит, оценку рисков ИБ, а также оценку текущего состояния процессов обеспечения информационной безопасности

### Услуги в области построения ситуационных центров по информационной безопасности (SOC)

-Услуги по техническому сопровождению продуктов и процессов ситуационных центров мониторинга ИБ

-Формализация процессов управления инцидентами ИБ в рамках ситуационных центров

### Защита объектов КИИ

-Проведение комплекса работ по приведению системы защиты АСУ ТП предприятий в соответствие требованиям 187-ФЗ, в том числе с учетом требований приказа ФСТЭК России № 31

-Организация подключения к ГосСОПКА

-Проектирование и внедрение системы защиты объектов КИИ в соответствии с Приказами ФСТЭК № 235 и № 239

-Разработка модели угроз и нарушителя

-Проведение категорирования объектов КИИ

### Внедрение систем защиты информации

В рамках внедрения средств и систем защиты информации компания предлагает следующие варианты предоставления услуг:

-проведение пилотных проектов с подготовкой плана тестирования, оказание консультаций и помощи в выборе СрЗИ, разработка отчетов, проведение презентаций, подготовка ТТ / ТЗ;

-обследование и аудит существующей ИТ и ИБ инфраструктуры;

-выполнение работ по техническому проектированию систем защиты информации;

-подготовка ЭД / РД / исполнительской документации;

-проведение строительно-монтажных и пуско-наладочных работ, внедрение сложных комплексных систем, модернизация существующих СЗИ;

-проведение опытной эксплуатации;

-проведение приемо-сдаточных испытаний.

### Техническое сопровождение и поддержка средств и систем защиты информации

Компания «ДиалогНаука» оказывает следующие услуги по технической поддержке средств и систем защиты информации:

-проведение периодического аудита и профилактического обслуживания средств и систем защиты информации;

-услуги мониторинга состояния компонентов средств и систем защиты информации с возможностью оперативного оповещения и реагирования на нарушение их штатного функционирования;

-установка и контроль корректности применения обновлений программного обеспечения средств защиты информации

-выполнение работ по изменению конфигурации средств защиты информации с предварительной оценкой рисков

-анализ и диагностика нештатных ситуаций в работе средств защиты информации с выработкой рекомендаций

-оказание содействия в расследованиях инцидентов информационной безопасности с предоставлением экспертного заключения с целью исключения повторения инцидента.

### Astra Linux Образовательный интернет-портал для дистанционного обучения

Все желающие могут зайти на портал в качестве гостей, ознакомиться с перечнем доступных курсов, их основным содержанием и учебными материалами открытой части «Справочного центра» — базы знаний Astra Linux с наиболее востребованной информацией о программных продуктах  компании. Непосредственно пройти обучение и тестирование могут клиенты, которые его заказали через авторизованные учебные центры Astra Linux, им предоставляются учетные данные для полного доступа.

### Сетевая безопасность (песочницы, IDS, cистемы многопоточного выявления вредоносного контента, средства контроля доступа в сеть Интернет, межсетевые экраны, СКЗИ)

-Системы для безопасного обмена файлами

-Средства криптографической защиты информации

-Системы обнаружения сетевых атак

-Межсетевые экраны

-Средства контроля доступа в сеть Интернет

-Системы многопоточного выявления вредоносного контента

-Системы защиты от целенаправленных атак («песочницы»)

### Защита рабочих станций и серверов (антивирусы, MDM, СЗИ от НСД, Deception, EDR)

-Средства выявления и реагирования на инциденты на уровне АРМ (EDR)

-Обманные системы (Deception)

-Средства защиты от несанкционированного доступа

-Средства защиты мобильных устройств (Mobile Device Management)

-Средства антивирусной защиты

### Защита от внутреннего нарушителя (DLP, PAM, DCAP/DAG)

-Средства контроля доступа к неструктурированным данным (DCAP, DAG)

-Системы контроля и защиты от несанкционированного распространения документов Information Leaks Detection (ILD)

-Средства контроля действий администраторов

-Средства для защиты от утечки конфиденциальной информации (DLP)

### Мониторинг и реагирование (SOC) (SIEM, UEBA, SOAR, TI)

-Системы мониторинга сетевого трафика NTA (Network Traffic Analysis)

-Платформы для киберразведки

-Средства автоматизации реагирования на инциденты (SOAR)

-Средства поведенческой аналитики (UEBA)

-Системы мониторинга событий информационной безопасности

### Анализ защищенности (системы анализа уязвимостей, средства автоматизации pentest'ов, системы визуализации и анализа рисков безопасности)

-Средства для автоматизации pentest’ов

-Средства анализа уязвимостей

### Защита приложений (WAF, DBF)

-Межсетевые экраны прикладного уровня для защиты баз данных

-Межсетевые экраны прикладного уровня для защиты веб-серверов

### Защита АСУ ТП (СЗИ, связанные с защитой КИИ)

-Средства защиты АСУ ТП

Информация взята с сайтов - https://www.dialognauka.ru/services/ и https://www.dialognauka.ru/solutions/

## Шаг 4. Клиенты компании

ПАО «Ростелеком»
ФГУП «Госкорпорация по ОрВД»
«Газпромбанк» (Акционерное общество) / Банк ГПБ (АО)
Банк ВТБ (ПАО)
МГФОМС
ПАО АКБ «Абсолют Банк»
АО «Банк ФИНАМ»
ДИТ города Москвы
X5 Retail Group N.V.
АО «Альфа-Банк»
АО «Россельхозбанк»
РНКБ Банк (ПАО)
АО «Международный аэропорт Шереметьево»
ПАО РОСБАНК
Госкорпорация «Роскосмос»
АО «Кредит Европа Банк (Россия)»
ПАО «МТС»
ТрансКапиталБанк / ТКБ БАНК ПАО
ООО «К-телеком»
АО «Аэромар»
Федеральный фонд обязательного медицинского страхования / ФОМС
ФГУП «Росморпорт»
Государственная транспортная лизинговая компания / АО «ГТЛК»
ПАО «Дальневосточное морское пароходство»
ПАО «Аэрофлот»
«Сетелем Банк» ООО
ООО «Фольксваген Банк РУС»
АО «Ури Банк»
Банк России / ЦБ РФ
АО «РН Банк»
АО «Почта Банк»
Эс-Би-Ай Банк ООО (SBI Bank LLC)
АО АКБ «ЦентроКредит»
АО БАНК «СНГБ»
АО «Кубаньторгбанк»
АО «Денизбанк Москва»
ООО «Компания БКС»
Объединенное Кредитное Бюро / АО «ОКБ»
«ИНТЕРПРОГРЕССБАНК» (Акционерное общество)
Национальная Система Платежных Карт / АО «НСПК»
ООО «БМВ Банк»
АО «Kaspi Bank»
АО «Частные Активы»
ПАО Московская Биржа
ОАО «Белгазпромбанк»
АО Холдинг ВТБ Капитал
ПАО Банк «ФК Открытие»
«Азиатско-Тихоокеанский Банк» (АО)
AО КБ «АГРОПРОМКРЕДИТ»
ООО «Т2 Мобайл»
АО «МаксимаТелеком»
ПАО «ВымпелКом»
АО «Азимут»
АО «Атомредметзолото»
АО «Концерн «Калашников»
ПАО «Сегежа Групп»
АО «Концерн ВКО «Алмаз-Антей»
АО «ОМК»
ПАО «НЛМК»
АО «НПФ Эволюция»
АО «НПФ «Транснефть»
АО «НПФ Сбербанка»
ООО СК «Росгосстрах Жизнь»
ООО «СК СОГАЗ-ЖИЗНЬ»
АО «Страховая компания «СОГАЗ-Мед»
Государственная корпорация по атомной энергии «Росатом»
«Россети ФСК ЕЭС» / ПАО «Россети»
ПАО «ТГК-1»
ФГКУ ГИВЦ Росрезерва
ФГБУ ИАЦ Судебного департамента
ФГУП «ГРЧЦ»
ГБУЗ «МГОБ № 62 ДЗМ»
Национальное бюро кредитных историй / АО «НБКИ»
ИНВЕСТТОРГБАНК АО
«Сирена-Трэвел»
АО «КБ «Солидарность»
АКБ «Ланта-Банк» (АО)
ПАО Сбербанк
Аппарат Совета Федерации Федерального Собрания РФ
Аппарат Государственной Думы Федерального Собрания РФ
Министерство обороны РФ
Министерство экономического развития РФ
Министерство транспорта РФ
Министерство иностранных дел РФ
ГК «Агентство по страхованию вкладов»
Управление Судебного департамента при Верховном суде РФ
Московская областная Дума
Администрация Ханты-Мансийского автономного округа
Министерство внутренних дел РФ
Федеральная служба охраны при Президенте РФ
Пенсионный фонд РФ
ФГУП «Гознак»
Федеральная налоговая служба
Федеральный центр информатизации при ЦИК России
Государственная корпорация «Ростех»
ООО «Нэт Пэй»
ООО «СК «Согласие»
ООО СК «ВТБ Страхование»
АО «ГСК «Югория»
ПАО СК «Росгосстрах»
АО «СОГАЗ»
OBI
ООО «Лента»
ООО «Хендэ Мотор СНГ»
ПАО «ГМК «Норильский никель»
АО «Вертолёты России»
ПАО МГТС
ПАО «МегаФон»
АО «РТКомм.РУ»
ПАО «РусГидро»
ПАО «НОВАТЭК»
АО «Объединенная энергетическая компания»
ПАО «МОЭСК» / ПАО «Россети Московский регион»
ПАО АНК «Башнефть»
АО «Тинькофф Банк»
«Национальная служба взыскания» / ООО «НСВ»
ПАО «Запсибкомбанк»
АО «ОТП Банк»
«Национальный расчетный депозитарий» / НКО АО НРД
ПАО «МТС-Банк»
ПAO «Промсвязьбанк»
АО «Банк Русский Стандарт»
ПАО «Банк «Санкт-Петербург»

Информация взта с сайта - https://www.dialognauka.ru/about/clients/

## Шаг 3. Веб-сайты компании и сотрудников

Главный веб-сайт компании - https://www.dialognauka.ru/ 

## Шаг 4. Публичные сотрудники компании

## Генеральный директор - Сердюк Виктор Александрович

Виктор родился 24 июля 1981 года.

В 2003 году получил образование в МАТИ-РГТУ им. К.Э.Циолковского, где обучался на кафедре «Информационные технологии».

Защитил кандидатскую диссертацию по информационной безопасности (ИБ).

С 2001 по 2006 год работал в ЗАО «РНТ» - руководил консалтинговыми проектами в сфере ИБ для ключевых клиентов.

Окончил программу MBA в АНХ. Преподает курсы лекций по ИБ в МАТИ-РГТУ, доцент.

Информация взята с сайта - https://www.tadviser.ru/index.php/%D0%9F%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0:%D0%A1%D0%B5%D1%80%D0%B4%D1%8E%D0%BA_%D0%92%D0%B8%D0%BA%D1%82%D0%BE%D1%80_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87

### Другие сотрудники компании

Мальцев Тимофей Юрьевич - Заместитель генерального директора по общим вопросам

Петров Николай Николаевич - Заместитель генерального директора по коммерческим вопросам

Печников Александр Владимирович - Директор по маркетингу

Свинцицкий Антон Игоревич - Директор по консалтингу

Ванерке Роман Михайлович - Технический директор

## Шаг 7. Достижения компании

15 февраля 2022 - Завершен проект по подготовке к сертификационному аудиту системы управления информационной безопасностью (СУИБ) AKKUYU NÜKLEER ANONIM ŞIRKETI в соответствие с требованиями ISO/IEC 27001:2013. Заказчиком услуг выступила первая на средиземноморском побережье Турции атомная электростанция

21 сентября 2020 - Завершена научно-исследовательская работа в сфере обязательного медицинского страхования для нужд Федерального фонда обязательного медицинского страхования (далее – ФОМС) по разработке предложений по созданию вертикально-интегрированной системы взаимодействия ФОМС и ТФОМС с ГосСОПКА

17 сентября 2019 - Подтверждение статуса участника Программы ассоциированных консультантов Британского Института Стандартов (BSI ACP).

4 декабря 2018 - Вхождение в состав одного из пяти подкомитетов Технического комитета № 122 – «Безопасность финансовых (банковских) операций» (ПК1).

4 декабря 2017 - Завершен крупный проект для АО «Объединенная энергетическая компания» по созданию уникальной по своей сложности и комплексности Системы обеспечения информационной безопасности (СОИБ) Автоматизированной системы технологического управления (АСТУ).